//! Integration tests for the Axum adapter's stateful (session-based) wiring.
//!
//! `authkestra-engine`'s own tests exercise `AuthMethod`/`Flow`/`Provider`
//! implementations and `OAuth2Flow` directly (see
//! `authkestra-engine/tests/oauth2_flow_tests.rs`). Those tests never touch
//! `authkestra-axum`, so they can't catch adapter-level regressions: state
//! extraction via `FromRef` (generated by `#[derive(AxumState)]`), the
//! `tower_cookies` wiring, or the `AxumError -> Response` mapping.
//!
//! These tests build a real `axum::Router` — the same one an application
//! would build with `Engine::axum_router()` — and drive it with
//! `tower::ServiceExt::oneshot`, asserting on actual HTTP responses (status
//! codes, `Set-Cookie`/`Location` headers, JSON bodies) rather than calling
//! engine internals directly.
//!
//! The OAuth provider is a fully in-process mock (no network, no wiremock)
//! so the flow is deterministic: `authkestra-providers` already has its own
//! wiremock-backed tests for the real provider implementations.

use async_trait::async_trait;
use authkestra_axum::{AuthSession, AxumExt, AxumState};
use authkestra_engine::auth::{
    AuthError, Identity, OAuthProvider, OAuthToken, Provider, ProviderConfig, Session, SessionStore,
};
use authkestra_engine::flow::{Engine, OAuth2Flow};
use authkestra_engine::{AkWebAppEngine, SessionConfig};
use axum::{
    body::Body,
    http::{header, Request, StatusCode},
    response::IntoResponse,
    routing::get,
    Json, Router,
};
use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use tower::ServiceExt;
use tower_cookies::CookieManagerLayer;

/// A deterministic, in-process stand-in for a real OAuth2 provider.
///
/// Only `"valid-code"` exchanges successfully, mirroring the pattern used by
/// `authkestra-engine`'s own `oauth2_flow_tests.rs` mock.
struct MockOAuthProvider;

#[async_trait]
impl Provider for MockOAuthProvider {
    async fn config(&self) -> ProviderConfig {
        ProviderConfig {
            id: "mock".to_string(),
            name: "Mock".to_string(),
            extra: HashMap::new(),
        }
    }
}

#[async_trait]
impl OAuthProvider for MockOAuthProvider {
    fn provider_id(&self) -> &str {
        "mock"
    }

    fn get_authorization_url(
        &self,
        state: &str,
        _scopes: &[&str],
        _code_challenge: Option<&str>,
        _nonce: Option<&str>,
    ) -> String {
        format!("https://mock.example.com/authorize?state={state}")
    }

    async fn exchange_code_for_identity(
        &self,
        code: &str,
        _code_verifier: Option<&str>,
        nonce: Option<&str>,
    ) -> Result<(Identity, OAuthToken), AuthError> {
        if code != "valid-code" {
            return Err(AuthError::Token("invalid code".to_string()));
        }

        let mut attributes = HashMap::new();
        // OAuth2Flow::finalize_login rejects the exchange if the identity
        // doesn't echo back the nonce it generated, so a well-behaved
        // provider mock must round-trip it exactly like a real one would.
        if let Some(n) = nonce {
            attributes.insert("nonce".to_string(), n.to_string());
        }

        Ok((
            Identity {
                provider_id: "mock".to_string(),
                external_id: "user-42".to_string(),
                email: Some("user@example.com".to_string()),
                username: Some("mockuser".to_string()),
                attributes,
            },
            OAuthToken {
                access_token: "at-123".to_string(),
                token_type: "Bearer".to_string(),
                expires_in: Some(3600),
                refresh_token: None,
                scope: None,
                id_token: None,
            },
        ))
    }
}

/// A minimal in-memory `SessionStore`, independent of
/// `authkestra_engine::store::memory::MemoryStore` (which sits behind the
/// `memory` feature) so this test only needs the features it declares via
/// `required-features` in `Cargo.toml`.
#[derive(Default)]
struct TestSessionStore {
    sessions: Mutex<HashMap<String, Session>>,
}

#[async_trait]
impl SessionStore for TestSessionStore {
    async fn load_session(&self, id: &str) -> Result<Option<Session>, AuthError> {
        Ok(self.sessions.lock().unwrap().get(id).cloned())
    }

    async fn save_session(&self, session: &Session) -> Result<(), AuthError> {
        self.sessions
            .lock()
            .unwrap()
            .insert(session.id.clone(), session.clone());
        Ok(())
    }

    async fn delete_session(&self, id: &str) -> Result<(), AuthError> {
        self.sessions.lock().unwrap().remove(id);
        Ok(())
    }
}

#[derive(Clone, AxumState)]
struct AppState {
    #[authkestra(engine)]
    auth: AkWebAppEngine,
}

async fn protected(AuthSession(session): AuthSession) -> impl IntoResponse {
    Json(serde_json::json!({
        "external_id": session.identity.external_id,
        "email": session.identity.email,
        "provider": session.identity.provider_id,
    }))
}

/// Builds the same shape of app a real application would: the engine's
/// generated `/auth/login/:provider`, `/auth/callback/:provider`, and
/// `/auth/logout` routes, plus one application route protected by
/// `AuthSession`.
fn build_app() -> Router {
    let session_store: Arc<dyn SessionStore> = Arc::new(TestSessionStore::default());
    let engine = Engine::builder()
        .provider(OAuth2Flow::new(MockOAuthProvider))
        .session_store(session_store)
        .session_config(SessionConfig {
            // The test client talks plain HTTP; a `Secure` cookie would
            // never round-trip back to the server.
            secure: false,
            ..Default::default()
        })
        .build();
    let state = AppState {
        auth: engine.clone(),
    };

    Router::new()
        .route("/protected", get(protected))
        .merge(engine.axum_router())
        .layer(CookieManagerLayer::new())
        .with_state(state)
}

/// Extracts the value of the first `Set-Cookie` header matching `name` from
/// a response (ignoring cookie attributes like `Path`/`HttpOnly`).
fn set_cookie_value(resp: &axum::response::Response, name: &str) -> Option<String> {
    resp.headers()
        .get_all(header::SET_COOKIE)
        .iter()
        .filter_map(|v| v.to_str().ok())
        .find_map(|raw| {
            let (key, value) = raw.split_once(';').unwrap_or((raw, "")).0.split_once('=')?;
            (key == name).then(|| value.to_string())
        })
}

async fn body_json(resp: axum::response::Response) -> serde_json::Value {
    let bytes = axum::body::to_bytes(resp.into_body(), usize::MAX)
        .await
        .unwrap();
    serde_json::from_slice(&bytes).unwrap()
}

#[tokio::test]
async fn protected_route_rejects_request_without_session_cookie() {
    let app = build_app();

    let resp = app
        .oneshot(
            Request::builder()
                .uri("/protected")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

    assert_eq!(resp.status(), StatusCode::UNAUTHORIZED);
}

#[tokio::test]
async fn full_login_callback_session_and_logout_round_trip() {
    let app = build_app();

    // 1. Login initiates the flow: a redirect to the provider, plus an
    //    encrypted `ak_state` CSRF cookie the callback must see again.
    let login_resp = app
        .clone()
        .oneshot(
            Request::builder()
                .uri("/auth/login/mock")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(login_resp.status(), StatusCode::SEE_OTHER);

    let location = login_resp
        .headers()
        .get(header::LOCATION)
        .unwrap()
        .to_str()
        .unwrap()
        .to_string();
    assert!(
        location.starts_with("https://mock.example.com/authorize?state="),
        "unexpected redirect location: {location}"
    );
    let csrf_state = location.rsplit('=').next().unwrap().to_string();

    let ak_state_cookie =
        set_cookie_value(&login_resp, "ak_state").expect("login must set the ak_state CSRF cookie");

    // 2. Callback: present the CSRF cookie, the matching `state`, and a code
    //    the mock provider accepts.
    let callback_resp = app
        .clone()
        .oneshot(
            Request::builder()
                .uri(format!(
                    "/auth/callback/mock?code=valid-code&state={csrf_state}"
                ))
                .header(header::COOKIE, format!("ak_state={ak_state_cookie}"))
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(callback_resp.status(), StatusCode::SEE_OTHER);

    let session_cookie = set_cookie_value(&callback_resp, "authkestra_session")
        .expect("a successful callback must set the session cookie");

    // 3. The protected route now succeeds and returns the identity that came
    //    back from the (mock) provider.
    let protected_resp = app
        .clone()
        .oneshot(
            Request::builder()
                .uri("/protected")
                .header(
                    header::COOKIE,
                    format!("authkestra_session={session_cookie}"),
                )
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(protected_resp.status(), StatusCode::OK);
    let json = body_json(protected_resp).await;
    assert_eq!(json["external_id"], "user-42");
    assert_eq!(json["email"], "user@example.com");
    assert_eq!(json["provider"], "mock");

    // 4. Logout deletes the session server-side...
    let logout_resp = app
        .clone()
        .oneshot(
            Request::builder()
                .uri("/auth/logout")
                .header(
                    header::COOKIE,
                    format!("authkestra_session={session_cookie}"),
                )
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(logout_resp.status(), StatusCode::SEE_OTHER);

    // 5. ...so presenting the very same session cookie again is rejected.
    let after_logout_resp = app
        .oneshot(
            Request::builder()
                .uri("/protected")
                .header(
                    header::COOKIE,
                    format!("authkestra_session={session_cookie}"),
                )
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(after_logout_resp.status(), StatusCode::UNAUTHORIZED);
}

#[tokio::test]
async fn callback_rejects_mismatched_csrf_state() {
    let app = build_app();

    let login_resp = app
        .clone()
        .oneshot(
            Request::builder()
                .uri("/auth/login/mock")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    let ak_state_cookie = set_cookie_value(&login_resp, "ak_state").unwrap();

    // The `state` query param doesn't match the one encrypted into the
    // `ak_state` cookie: this must be treated as a CSRF failure, not
    // silently accepted.
    let callback_resp = app
        .oneshot(
            Request::builder()
                .uri("/auth/callback/mock?code=valid-code&state=not-the-real-state")
                .header(header::COOKIE, format!("ak_state={ak_state_cookie}"))
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

    assert_eq!(callback_resp.status(), StatusCode::UNAUTHORIZED);
}

#[tokio::test]
async fn callback_rejects_missing_csrf_cookie() {
    let app = build_app();

    // No `ak_state` cookie at all (e.g. the user opened the callback link
    // directly, or cookies were dropped in transit).
    let callback_resp = app
        .oneshot(
            Request::builder()
                .uri("/auth/callback/mock?code=valid-code&state=whatever")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

    assert_eq!(callback_resp.status(), StatusCode::UNAUTHORIZED);
}

#[tokio::test]
async fn callback_rejects_provider_exchange_failure() {
    let app = build_app();

    let login_resp = app
        .clone()
        .oneshot(
            Request::builder()
                .uri("/auth/login/mock")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    let location = login_resp
        .headers()
        .get(header::LOCATION)
        .unwrap()
        .to_str()
        .unwrap()
        .to_string();
    let csrf_state = location.rsplit('=').next().unwrap().to_string();
    let ak_state_cookie = set_cookie_value(&login_resp, "ak_state").unwrap();

    // A code the mock provider doesn't recognize as valid.
    let callback_resp = app
        .oneshot(
            Request::builder()
                .uri(format!(
                    "/auth/callback/mock?code=wrong-code&state={csrf_state}"
                ))
                .header(header::COOKIE, format!("ak_state={ak_state_cookie}"))
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

    assert_eq!(callback_resp.status(), StatusCode::UNAUTHORIZED);
}
