[package]
name = "authkestra-store-testsuite"
edition.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
exclude.workspace = true

[dependencies]
authkestra-engine = { path = "../authkestra-engine" }
authkestra-op = { path = "../authkestra-op" }
authkestra-resource = { path = "../authkestra-resource" }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
