[package]
name = "axum-mfa-server"
version = "0.1.0"
edition = "2021"

[dependencies]
authkestra-engine = { path = "../../crates/authkestra-engine", features = ["memory", "totp", "webauthn"] }
authkestra-axum = { path = "../../crates/authkestra-axum" }
axum = "0.7.5"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
webauthn-rs = { version = "0.5.0", features = ["danger-allow-state-serialisation"] }
url = "2.5"
async-trait = "0.1"
